<?php
class Usercontr extends Users{



    public function createStudentAccount($name, $surname, $loginID, $password, $user_role, $active_status, $reg_status, $joined){
        $this->setStudentAccount($name, $surname, $loginID, $password, $user_role, $active_status, $reg_status, $joined);
    }

    public function createIndexUserRow($loginID, $name, $surname){
        $this->setIndexUserRow($loginID, $name, $surname);
    }
	
	public function autologinSet($id, $loginID){
		$this->autoLogin($id, $loginID);
	}

    public function autologinUsers($id, $loginID){
        parent::autoLoginUsers($id, $loginID);
    }

    public function UpdateRegStatus($regStatus, $id)
    {
        parent::UpdateRegStatus($regStatus, $id); // TODO: Change the autogenerated stub
    }

    public function Stage4($id){
        parent::Stage4($id);
    }

    public function Stage3($institute, $program, $programType, $dateStart, $dateEnd, $id){
        parent::Stage3($institute, $program, $programType, $dateStart, $dateEnd, $id);
    }

    public function Stage2($DOB, $marital, $gender, $phone, $email, $country, $religion, $about, $id){
        parent::Stage2($DOB, $marital, $gender, $phone, $email, $country, $religion, $about, $id);
    }

    public function SigninUser($loginID, $password){
        parent::SigninUser($loginID, $password);
    }

    public function log_out(){
        // Destroy and unset active session
        session_destroy();
        unset($_SESSION['id']);
        unset($_SESSION['name']);
        unset($_SESSION['surname']);
        unset($_SESSION['email']);
        unset($_SESSION['role']);
        unset($_SESSION['status']);
        echo "<script type='text/javascript'>
      window.location='index.php';
      </script>";
        return true;
    }

}
